# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Soma Sundaram
title: Senior Database Engineer
email: soma.bss@gmail.com
website: https://www.linkedin.com/in/somasundaram1/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: somabss1
github_username:  CodeScribbl
linkedin_username: somasundaram1
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Soma and I'm a senior Data Engineer. Highly experienced data professional with 20+ years in data engineering and database administration. Proven ability to design and implement scalable data solutions, lead cross-functional teams, and drive data-informed decision-making. AWS Certified with expertise in different Database technologies - Open source Databases[RDBMS/Distributed Databases/NoSQL/Vector Databases], Data Engineering technologies [ETL, Analytics and Modern Data engineering Stack] and Python. I have worked at a number of companies gaining teamwork and leadership skills.

  I am passionate about : <mark>Cloud technologies [AWS/GCP]</mark>, <mark>System Design</mark>, <mark>Gen AI and ML/MLOPS</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Agentic AI - Sentiment Analysis for Ticketing system
        link: https://www.linkedin.com/posts/somasundaram1_ai-sentimentanalysis-haystack-activity-7240559522514186240-4sR0
        link_text: Linkedin Post
        additional_links:
          - title:  Linkedin Post
            icon: fab fa-Linkedin
            url: https://www.linkedin.com/posts/somasundaram1_ai-sentimentanalysis-haystack-activity-7240559522514186240-4sR0
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          "Just as electricity transformed almost everything 100 years ago, today I actually have a hard time thinking of an industry that I don’t think AI will transform in the next several years."" - Andrew Ng
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>AI ML technologies</mark> and it has helped to showcase my skills in my organization's Hackweek. I have learned many skills through this project such as considerations for Data security and evaluated tools available for data security in the AI Pipeline, Agentic AI Pipeline frameworks [LlamaIndex/Haystack]. I'm very proud of having this in my portfolio. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fiserv, Inc
        link: www.fiserv.com
        # link_text: boringcompany.com
        sub_title: Senior Database Administration - Advisor 
        caption: December 2019 - Present
        quote: >
            As part of this role, my role is to help the organization scale the Enterprise Database Infrastructure and Data Engineering Solutions.
        description: | # this will include new lines to allow paragraphs
            Database Advisory professional skilled in application database design and Data Engineering Solutions. Proficient in Data Engineering, Analytics, Database Administration [On-Prem and Cloud Databases]. 

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: AWS Certified Solutions Architect - Associate
        link: https://www.credly.com/badges/770ea617-ec45-48d7-afd7-74970a369662
        link_text: Credly
      - layout: top-middle
        title: AWS Certified Database Speciatly
        link: https://www.credly.com/badges/61aa7ec3-5819-4e4b-aa78-b3de8fb0d026
        link_text: Credly
        #caption: 2010 - 2013
        #sub_title: BSc Computer Science
        #quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        #description: | # this will include new lines to allow paragraphs
#         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
#         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Databases, Data Engineering and AI/ML technologies, some of my other interests and hobbies are:
      - Hiking
      - Running
      - Poker
      - [Markets](https://musingsandmarketwatch.substack.com)
#     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
